services:
    wandi_tools.form:
        class: Wandi\ToolsBundle\Util\Form

    wandi_tools.string:
        class: Wandi\ToolsBundle\Util\Str

    wandi_tools.format:
        class: Wandi\ToolsBundle\Util\Format

    wandi_tools.host_parser:
        class: Wandi\ToolsBundle\Util\HostParser

    wandi_tools.twig.extension.various:
        class: Wandi\ToolsBundle\Twig\Extension\VariousExtension
        tags:
            - { name: twig.extension }
        arguments: ['@wandi_tools.string', '@wandi_tools.format', '@wandi_tools.form']

    wandi_tools.token_generator:
        class: Wandi\ToolsBundle\Util\TokenGenerator\TokenGenerator

    wandi_tools.files_manager:
        class: Wandi\ToolsBundle\Util\FilesManager
