services:
    Wandi\ToolsBundle\Util\Strings:
    wandi_tools.strings:
        alias: Wandi\ToolsBundle\Util\Strings
        public: true

    Wandi\ToolsBundle\Util\Formatter:
    wandi_tools.formatter:
        alias: Wandi\ToolsBundle\Util\Formatter
        public: true

    Wandi\ToolsBundle\Util\HostParser:
    wandi_tools.host_parser:
        alias: Wandi\ToolsBundle\Util\HostParser
        public: true

    Wandi\ToolsBundle\Twig\Extension\ToolsExtension:
        tags:
            - { name: twig.extension }

    wandi_tools.twig.extension.tools:
        alias: Wandi\ToolsBundle\Twig\Extension\ToolsExtension
        public: true

    Wandi\ToolsBundle\Util\TokenGenerator:
    wandi_tools.token_generator:
        alias: Wandi\ToolsBundle\Util\TokenGenerator
        public: true

    Wandi\ToolsBundle\Util\Files:
    wandi_tools.files:
        alias: Wandi\ToolsBundle\Util\Files
        public: true

    Wandi\ToolsBundle\Util\Sharer:
    wandi_tools.sharer:
        alias: Wandi\ToolsBundle\Util\Sharer
        public: true

    Wandi\ToolsBundle\Util\Arrays:
    wandi_tools.arrays:
        alias: Wandi\ToolsBundle\Util\Arrays
        public: true