services:
    wandi_tools.string:
        class: Wandi\ToolsBundle\Util\Str

    wandi_tools.format:
        class: Wandi\ToolsBundle\Util\Format
        arguments: ['@wandi_tools.string']

    wandi_tools.host_parser:
        class: Wandi\ToolsBundle\Util\HostParser

    wandi_tools.twig.extension.various:
        class: Wandi\ToolsBundle\Twig\Extension\Tools
        tags:
            - { name: twig.extension }
        arguments: ['@wandi_tools.string', '@wandi_tools.format']

    wandi_tools.token_generator:
        class: Wandi\ToolsBundle\Util\TokenGenerator

    wandi_tools.files_manager:
        class: Wandi\ToolsBundle\Util\FilesManager

    wandi_tools.referer:
        class: Wandi\ToolsBundle\Util\Referer
        arguments: ['@request_stack', '@router']

    wandi_tools.sharer:
        class: Wandi\ToolsBundle\Util\Sharer
        arguments: ['@request_stack']