services:
    Wandi\ToolsBundle\Tools\Str:

    wandi_tools.string:
        alias: Wandi\ToolsBundle\Tools\Str
        public: true

    Wandi\ToolsBundle\Tools\Format:
        arguments:
        - '@Wandi\ToolsBundle\Tools\Str'

    wandi_tools.format:
        alias: Wandi\ToolsBundle\Tools\Format
        public: true

    Wandi\ToolsBundle\Tools\HostParser:

    wandi_tools.host_parser:
        alias: Wandi\ToolsBundle\Tools\HostParser
        public: true

    Wandi\ToolsBundle\Twig\Extension\ToolsExtension:
        tags:
        - { name: twig.extension }
        arguments:
        - '@Wandi\ToolsBundle\Tools\Str'
        - '@Wandi\ToolsBundle\Tools\Format'

    wandi_tools.twig.extension.tools:
        alias: Wandi\ToolsBundle\Twig\Extension\ToolsExtension
        public: true

    Wandi\ToolsBundle\Tools\TokenGenerator:

    wandi_tools.token_generator:
        alias: Wandi\ToolsBundle\Tools\TokenGenerator
        public: true

    Wandi\ToolsBundle\Tools\FilesManager:

    wandi_tools.files_manager:
        alias: Wandi\ToolsBundle\Tools\FilesManager
        public: true

    Wandi\ToolsBundle\Tools\Referer:
        arguments:
        - '@request_stack'
        - '@router'

    wandi_tools.referer:
        alias: Wandi\ToolsBundle\Tools\Referer
        public: true

    Wandi\ToolsBundle\Tools\Sharer:
        arguments:
        - '@request_stack'

    wandi_tools.sharer:
        alias: Wandi\ToolsBundle\Tools\Sharer
        public: true
