services:
    wandi_tools.string:
        class: Wandi\ToolsBundle\Tools\Str

    wandi_tools.format:
        class: Wandi\ToolsBundle\Tools\Format
        arguments: ['@wandi_tools.string']

    wandi_tools.host_parser:
        class: Wandi\ToolsBundle\Tools\HostParser

    wandi_tools.twig.extension.tools:
        class: Wandi\ToolsBundle\Twig\Extension\ToolsExtension
        tags:
            - { name: twig.extension }
        arguments: ['@wandi_tools.string', '@wandi_tools.format']

    wandi_tools.token_generator:
        class: Wandi\ToolsBundle\Tools\TokenGenerator

    wandi_tools.files_manager:
        class: Wandi\ToolsBundle\Tools\FilesManager

    wandi_tools.referer:
        class: Wandi\ToolsBundle\Tools\Referer
        arguments: ['@request_stack', '@router']

    wandi_tools.sharer:
        class: Wandi\ToolsBundle\Tools\Sharer
        arguments: ['@request_stack']
