services:
    wandi_tools.string:
        class: Wandi\ToolsBundle\Services\Str

    wandi_tools.host_parser:
        class: Wandi\ToolsBundle\Services\HostParser

    wandi_tools.twig.vars:
        class: Wandi\ToolsBundle\Twig\Extension\VariousExtension
        tags:
            - { name: twig.extension }
        arguments: ['@wandi_tools.string']
