language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

install:
  - composer install

script:
  - ./vendor/bin/phpunit -v --stop-on-failure