branches:
  only:
    - legacy-stable
    - master
    - unstable

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - composer update --prefer-dist
  - composer require phpstan/phpstan

script:
  - ./vendor/bin/phpunit -v --stop-on-failure
  - ./vendor/bin/phpstan analyse . --level=3